# Generated by Django 6.0.1 on 2026-04-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_sessionfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sessionfile",
            options={},
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.chatsession"
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="file_size",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="file_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sessionfile",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.chatsession"
            ),
        ),
        migrations.CreateModel(
            name="SessionMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_memory",
                        to="chat.chatsession",
                    ),
                ),
            ],
        ),
    ]
